### ISSUE TITLE
[DESIGN] Design Gas Tank UI

### ISSUE THREAD

**Issue by dmcong** [Desig-Labs/desig-assets#1]

**Comment by Dongbt113** [comment]
https://www.figma.com/file/cWLwTPX0Z5z4atN3aZw7Jf/Desig?type=design&node-id=12372%3A59059&mode=design&t=qUe186zfpJ4FBMjr-1

**Comment by Dongbt113** [comment]
![Image](https://github.com/Desig-Labs/desig-assets/assets/126558663/0fe85569-6541-4ea1-9065-ebf061259b17)



![Image](https://github.com/Desig-Labs/desig-assets/assets/126558663/7d235e87-76bf-4ba1-bb5a-a654a078d545)



![Image](https://github.com/Desig-Labs/desig-assets/assets/126558663/584c0245-77d0-4b77-b67c-9d29c99d1f96)
