### ISSUE TITLE
Guild War Update - đã bàn vs a Công

### ISSUE THREAD

**Issue by cindra29** [Desig-Labs/desig-assets#103]
1. Buff theo độ chênh lệch size giữa guild nhỏ và guild lớn khi tấn công cho guild nhỏ
2. Khi send troops mún x2 thì sẽ tốn CANDY 
3. Mỗi giờ số troops sẽ bị giảm đi 1% 
4. Cho tính năng rút quân về, tốn 1 tiếng

**Comment by dmcong** [comment]
- Send troop tấn công, có thể x2 điểm = 450 candy
- Điểm = troop * (thành viên guild bị tấn công / thành viên guild tấn công => max 5, min 1) 
- Cron hằng giờ, giảm troop trong WW 1%
- đếm số cuộc tấn công và phòng thủ, hiển thị ngoài danh sách

**Comment by dmcong** [comment]
a @dongbui303  khi nào có UI tính năng này thế a

**Comment by ducmanh1101** [comment]
Tính toán số lượng lính gửi đi theo độ chênh lệch của guild:
- Cost BEE: 1:1 với số bee bỏ ra
- Bonus Troops: theo độ chênh lệch của guild (Wonder không có guild hoặc wonder đó là của guild mình thì bằng 0)
-> total: Cost + Bonus

Use case: Khi đi đánh wonder khác
- hp = 0 -> hp = cost (đổi owner)
- hp < cost   =>   hp = cost - hp (đổi owner)
- cost < hp < total   =>   hp =  0 (đổi owner)
- hp > total   =>   hp = total - hp
@dmcong

**Comment by ducmanh1101** [comment]
BE: https://github.com/Desig-Labs/berasig-server/pull/105
FE: https://github.com/Desig-Labs/bera-bee-catcher/pull/54
