### ISSUE TITLE
Kết quả của Bitget Campaign

### ISSUE THREAD

**Issue by cindra29** [Desig-Labs/desig-assets#125]
Cho tụi em xin list wallet address + tổng số tiền đã mua của từng người

**Comment by ducmanh1101** [comment]
Func: 
![Image](https://github.com/user-attachments/assets/3cd9d142-10e4-480c-973c-27e84e519871)

**Comment by ducmanh1101** [comment]
Result: 
[bitget-campaign.json](https://github.com/user-attachments/files/17110994/bitget-campaign.json)
[bitget-campaign.xlsx](https://github.com/user-attachments/files/17110999/bitget-campaign.xlsx)
cc @cindra29
