### ISSUE TITLE
[FIX] Cashflow - out app when click to cashflow

### ISSUE THREAD

**Issue by Coconut258** [Desig-Labs/desig-assets#33]
The crashing if we press Cashflow - Ticket 770 [Discord]

https://github.com/Desig-Labs/desig-assets/assets/135295387/e059490c-c519-4f1f-ac0f-af2ef2f7769d

**Comment by hnquan8** [comment]
- Check on the iOS device, it is normally
- Check on the Android device, it is bugging out when clicking on cashflow
