### ISSUE TITLE
[Gas Tank] History isn't showing up

### ISSUE THREAD

**Issue by raenguyen** [Desig-Labs/desig-assets#49]
History bị mất hết phần cũ, chỉ hiện đúng 1 tx earn yield của ngày hôm nay mà số liệu cũng không chính xác (0.011 ETH là total balance chứ không phải yield trong 1 ngày)
Phiên bản: iOS cập nhật ngày 21/4/2024

![Image](https://github.com/Desig-Labs/desig-assets/assets/130336011/0cda549a-51fb-4429-a90e-53cbeb62e76c)

**Comment by dmcong** [comment]
This isn't a bug. It's due to the differences between each staging and production environment
