### ISSUE TITLE
User kêu SUGAR bị trừ nhưng ko nhận đc BEE

### ISSUE THREAD

**Issue by cindra29** [Desig-Labs/desig-assets#80]
Địa chỉ ví: 0xCa50376D7aD65028bE58b34D7281e0e2624Ee23C 

Check trên beratrail thấy bị trừ 600 SUGAR, là mua 2 gói 100 BEE, nó cứ bảo là nó bị trừ tiền nhưng mà chỉ nhận đc 100 BEE th -> check giùm em được ko? [

tx báo fail trên app mình
![Image](https://github.com/user-attachments/assets/2a4e9258-89d7-40aa-a6cc-b7e3b00182e6)

](url)

**Comment by ducmanh1101** [comment]
Em check thì thấy status của ticket đó là DONE rồi á. chị hỏi nó double check lại thử xem
