### ISSUE TITLE
API for Bitget

### ISSUE THREAD

**Issue by cindra29** [Desig-Labs/desig-assets#95]
Verify user mua tu 4$ tro len!!

**Comment by ducmanh1101** [comment]
RPC: https://api.berabeecatcher.com/tracking/purchase-shop
Method: GET
params: { 
   walletAddress: address user bbc
   minimum: minimum USD in candy Shop
   startDate: campaign start date (Format: 2024-01-01)
 }

Mục đích của API: Tracking trong quest
PR: https://github.com/Desig-Labs/berasig-server/pull/100
